<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">
	<?php	
		echo $this->formLabel($this->element->email->getName(), $this->element->email->getLabel());?>		

	<?php
		echo $this->{$this->element->email->helper}(
					$this->element->email->getName(),
					$this->element->email->getValue(),
					$this->element->email->getAttribs()
				);
	?>
	<?php 
		if(($this->element->email->getMessages())){ echo  $this->formErrors($this->element->email->getMessages());} 
	?>
	<br />    				
	<div class="clearfix">&nbsp;</div>			
	<?php echo $this->{$this->element->submit->helper}(
		$this->element->submit->getName(),
		$this->element->submit->getValue(),
		$this->element->submit->getAttribs()
	);?>
</form>

<script type="text/javascript">
	$(document).ready(function() {
		$('#<?php echo $this->element->getId(); ?>').validationEngine('attach', {promptPosition: "centerRight"});
	});
</script>