<h1>Password recovery</h1>
<div class="login_wrap">
		<!--afisare mesaje de eroare/succes-->
		<?php if (!empty($this->message)) : ?>
			<?php foreach ($this->message as $value) : ?>
				<center><?php echo $value; ?></center>
			<?php endforeach; ?>
			<div class="clear"></div>
		<?php endif; ?>
	<div class="clear"></div>
	<div class="login_form">
		<p>Type your email address</p>
		<?php echo $this->formForgotPassword; ?>
		<div class="clear"></div>

	</div>
</div>
