<div id="wrapper">
	<div id="left_content">
		<h3>Login</h3>
		<div class="clear"></div>
        <div class="feedback_message">
			<!--afisare mesaje de eroare/succes-->
			<?php if (!empty($this->message)) : ?>
				<?php foreach ($this->message as $value) : ?>
					<center><?php echo $value; ?></center>
				<?php endforeach; ?>
				<div class="clearfix">&nbsp;</div>
			<?php endif; ?>
		</div>
		<div class="clear"></div>
		<div class="forms">
			<?php echo $this->plugin_form_login; ?>
			<?php echo $this->plugin_form_cont; ?>			
		</div>
		<div class="clear"></div>		
	</div>
	<div id="right_content">
		<div class="initiate">
				<a class="initiate_icon" href="<?php echo WEBROOT ?>proiect" >
					<img src="<?php echo WEBROOT ?>/theme/o_idee_pentru_bucuresti/images/initiate_icon.png" alt="Initiate"/>
					<p>Initiaza un proiect</p>
				</a>
			</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>	
<div class="clear"></div>


