<div class="form_sidebar">
	<form class="addForms" method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">
		<div class="input_wrapper">	
		<!--BEGIN NUME -->
		<?php echo $this->{$this->element->control->helper}($this->element->control->getName(), $this->element->control->getValue(), $this->element->control->getAttribs());?>
		<?php
			echo $this->{$this->element->name->helper}(
						$this->element->name->getName(),
						$this->element->name->getValue(),					
						$this->element->name->getAttribs()					
					);
		?>
		<?php 
			if(($this->element->name->getMessages())){ echo  $this->formErrors($this->element->name->getMessages());} 
		?>
		</div>
		<div class="clear"></div>
                
                <div class="input_wrapper">	
		<!--BEGIN PRICE -->
		<?php
			echo $this->{$this->element->price->helper}(
						$this->element->price->getName(),
						$this->element->price->getValue(),					
						$this->element->price->getAttribs()					
					);
		?>
		<?php 
			if(($this->element->price->getMessages())){ echo  $this->formErrors($this->element->price->getMessages());} 
		?>
		</div>
		<div class="clear"></div>
                
		<div class="input_wrapper">	
		<?php
			echo $this->{$this->element->idGroup->helper}(
						$this->element->idGroup->getName(),
						$this->element->idGroup->getValue(),					
						$this->element->idGroup->getAttribs(),
						$this->element->idGroup->getMultiOptions()
					);
		?>
		<?php 
			if(($this->element->idGroup->getMessages())){ echo  $this->formErrors($this->element->idGroup->getMessages());} 
		?>   
<!--		<small>* CTRL+Click to select more options</small>-->
		</div>
                <div class="clear"></div>
                <div class="input_wrapper">
                <?php echo $this->{$this->element->date->helper}(
					$this->element->date->getName(),
					$this->element->date->getValue(),
					$this->element->date->getAttribs()
		);?>
                <?php 
			if(($this->element->date->getMessages())){ echo  $this->formErrors($this->element->date->getMessages());} 
		?>
                </div>
		<div class="clear"></div>   
                <div class="fileUpload btn btn-primary">
                        <!--BEGIN: Fisiere atasate -->			
                        <div><input type="file" id="attachedFiles" class="upload" name="attachedFiles" /></div>
                        <div class="load_file_inputs"></div> <!--	save uploaded files in hidden inputs-->
                        <table class="load_files"></table> <!--	show uploaded files-->
                        <!--END: Fisiere atasate -->
                </div>
		<div class="clear"></div>
		<div class="input_wrapper">
			<?php echo $this->{$this->element->submit->helper}(
			$this->element->submit->getName(),
			$this->element->submit->getValue(),
			$this->element->submit->getAttribs()
			);?>
		</div>
	</form>
</div>
<div id="confirmDefaultFileDelete" title="Confirm delete" style="display:none;">
	Do you confirm deleting this file?
</div>
<script type="text/javascript">	
$(document).ready(function() {
	//validation
	$('#<?php echo $this->element->getId();?>').validationEngine('attach', {promptPosition : "centerRight"});

	var maxQueueSize = 10;
	var queueSize = 0;
	 //BEGIN:UPLOAD FILES
	$('#attachedFiles').uploadify({
		'multi'				: false,
		'swf'				: '<?php echo WEBROOT; ?>theme/admin/js/uploadify/uploadify.swf',
		'uploader'			: '<?php echo WEBROOT ?>ajax/upload-project-files',
        'buttonText'                    : 'UPLOAD PROOF',
		'removeCompleted'	: true,	
		'scriptAccess'		: 'always',
                'width'    : 128,
		'formData'			: {'PHPSESSID' : '<?php echo session_id(); ?>'},		
		'onUploadSuccess'	: function(file, data, response) {
			try 
			{
				var items= eval('(' + data + ')');
			} catch (e) {}
			if(items) 
			{	
				if(items.success)
				{				
					$('.load_file_inputs').append('<input type="hidden" id="gallery_'+items.fileId+'" name="galleryFiles[]" value="'+items.fileId+'" />'); 
					// load files
					$.post('<?php echo WEBROOT ?>ajax/show-project-uploads/', {'fileId':items.fileId,'fileType':'file'}, function(dataFile) 
					{
						try 
						{
							var itemsFile = eval('(' + dataFile + ')');
						} catch (e) {}
						if(itemsFile) 
						{							
							$('.load_files').append(itemsFile);
						}
					});
				}else{
					alert(items.message);
				}	
			}				
		}			
	// Your options here
    });
	//END:UPLOAD FILES
	
	//BEGIN:Uploaded files delete		
	$(document).on('click','.deleteDefault', function() {		
			var valueId = $(this).attr('rel');
			$("#confirmDefaultFileDelete").dialog({
				bgiframe: true,
				height: 140,
				width: 400,
				modal: true,
				buttons:{
					'<?php echo Zend_Registry::get('translate')->_('yes'); ?>': function(){				
						$.get('<?php echo WEBROOT ?>ajax/delete-project-upload/fileId/'+valueId, function(dataFile) 
						{
							try 
							{
								var itemsFile = eval('(' + dataFile + ')');
							} catch (e) {}
							if(itemsFile) 
							{								
								$('#gallery_'+valueId).remove();								
								$('.defaultShow_'+valueId).remove();
							}
						});
						$(this).dialog('close').dialog('destroy');		
					},
					'<?php echo Zend_Registry::get('translate')->_('no'); ?>': function(){
						$(this).dialog('close').dialog('destroy');					
					}
				}
			});
			return false;		
	 });
	//END:Uploaded files delete
	//BEGIN:DATE SELECT
	var date = new Date(<?php echo date('Y') ?>,<?php echo date('m') ?>,<?php echo date('d') ?>);

	$('.newDate').text($.datepicker.formatDate( "dd/mm/yy", date));
	//$("#date").datepicker('setDate', 'today');
        
	$("#date").datepicker({
		onSelect: function(dateText, inst) {
			date = new Date(inst.selectedYear, inst.selectedMonth, inst.selectedDay);
			var finalDate = ($.datepicker.formatDate( "yy-mm-dd", date));
			$('.newDate').text(($.datepicker.formatDate( "dd/mm/yy", date)));
			$('#date').val($.datepicker.formatDate( "mm/dd/yy", date));//mm/dd/yy - usa style
		}
	});
        $('#date').datepicker('setDate', 'today');
	//END:DATE SELECT
});
</script>