<div id="center">
	<div class="main_wrap">
		<h1 class="main_title"><?php echo Zend_Registry::get('translate')->_('admin_administrators_change_password'); ?></h1>
		<button class="submit" onclick="location.href='<?php echo WEBROOT; ?>users '"<?php echo $this->type; ?> title="<?php echo Zend_Registry::get('translate')->_('back'); ?>"><?php echo Zend_Registry::get('translate')->_('back'); ?></button>
	</div>
	<?php echo $this->form;?>
</div>

<!--afisare mesaje de eroare/succes-->
<?php if(!empty($this->message)) : ?>
	<?php foreach($this->message as $value) : ?>
		<center><?php echo $value; ?></center>
	<?php endforeach; ?>
	<div class="clear"></div>
<?php endif; ?>
	