<div id="left">
	<div class="menu">
		<ul class="menu_ul">
			<?php echo $this->navigation()->menu()->setMaxDepth(0); ?> 
		</ul>
	</div>
</div>
<!--<div id="sub_nav">
	<div id="subnav_wrap" class="container_12">
		<div id="subnav" class=" grid_12">	
			//<?php if ($this->navigation()->menu()->setMaxDepth(0) != $this->navigation()->menu()->renderSubMenu()){?>
				//<?php echo $this->navigation()->menu()->renderSubMenu();?>	
			//<?php }?>
		</div>
	</div>
</div>-->
