<div id="center">
	<div class="main_wrap">
		<h1 class="main_title"><?php echo Zend_Registry::get('translate')->_('admin_edit'); ?></h1>
	</div>
	<?php echo $this->form; ?>
</div>
<!--afisare mesaje de eroare/succes-->
<?php if(!empty($this->message)) : ?>
	<?php foreach($this->message as $value) : ?>
		<center><?php echo $value; ?></center>
	<?php endforeach; ?>
	<div class="clear"></div>
<?php endif; ?>

<div id="right">
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#idGroup").uniform();
});
</script>







