<div id="center">
	<div class="main_wrap">
		<h1 class="main_title">Adauga rol</h1>
		<div class="list">
			<div class="utilizator">
				<?php if(!empty($this->message)):?>
					<?php foreach($this->message as $value):?>
						<center><?php echo $value; ?></center>
					<?php endforeach;?>
				<?php endif;?>

				<a class="button" href="<?php echo WEBROOT; ?>/role/index" title="Inapoi">Inapoi</a>	
				<?php echo $this->form;?>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div id="right">
	
</div>