<div id="center">
	<div class="utilizatori_wrap">
		<h1>Editeaza rol</h1>
		<div class="utilizatori_listare">
			<div class="utilizator">
				<!--afisare mesaje de eroare/succes-->
				<?php if(!empty($this->message)) : ?>
					<?php foreach($this->message as $value) : ?>
						<center><?php echo $value; ?></center>
					<?php endforeach; ?>
					<div class="clearfix">&nbsp;</div>
				<?php endif; ?>

				<a class="button" href="<?php echo WEBROOT; ?>/role/index" title="Inapoi">Inapoi</a>	
				<!--afisare formular	-->
				<?php echo $this->form;?>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div id="right">
	
</div>