<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
    ?>
	<link rel="icon" type="images/jpeg" href="<?php echo WEBROOT;?>/theme/10pteuropa/favicon.ico" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
<!--This is the styling for the error message for form validation-->
</head>
<body>		  
		<?php echo $this->layout()->content ?>
</body>
</html>