<div id="masterwrapper">
	<div id="page">
		<div id="header"></div>
		<div class="clear"></div>
		<div id="content">				
			<div class="contentTop">
				<div class="error_box">
					<h1>404</h1>
					<h3 class="apexbook">We are sorry  but the page was not found !</h3>						
					<a href="<?php echo WEBROOT; ?>" class="error_home_link"></a>  
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>