<?php
if (file_exists(APPLICATION_PUBLIC_PATH.'/media/files/'.$this->result)) {
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header("Content-Type: application/force-download");
    header('Content-Disposition: attachment; filename=' . urlencode(basename(APPLICATION_PUBLIC_PATH.'/media/files/'.$this->result)));
    // header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    header('Content-Length: ' . filesize(APPLICATION_PUBLIC_PATH.'/media/files/'.$this->result));
    ob_clean();
    flush();
    readfile(APPLICATION_PUBLIC_PATH.'/media/files/'.$this->result);
    exit;
}

?>