<div class="main_forms">
  <form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>" id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>" enctype="<?php echo $this->element->getEncType(); ?>">	
	<?php echo $this->{$this->element->control->helper}($this->element->control->getName(), $this->element->control->getValue(), $this->element->control->getAttribs());?>
	<div class="left_nowidth">
            <div class="input_wrapper">
            <!-- old pass -->
            <?php echo $this->formLabel($this->element->oldPassword->getName(), $this->element->oldPassword->getLabel());?>
            <?php echo $this->{$this->element->oldPassword->helper}(
			$this->element->oldPassword->getName(),
			$this->element->oldPassword->getValue(),
			$this->element->oldPassword->getAttribs()
		);
            ?>	
            <?php 
			if(($this->element->oldPassword->getMessages())){ echo  $this->formErrors($this->element->oldPassword->getMessages());} 
            ?>
            </div>
            <div class="clear"></div>	
            <!-- pass -->
            <div class="input_wrapper">
            <?php echo $this->formLabel($this->element->password->getName(), $this->element->password->getLabel());?>
            <?php echo $this->{$this->element->password->helper}(
			$this->element->password->getName(),
			$this->element->password->getValue(),
			$this->element->password->getAttribs()
		);
            ?>	
            <?php if(($this->element->password->getMessages())){ echo  $this->formErrors($this->element->password->getMessages());} ?>	
            </div>
            <div class="clear"></div>
            <!-- retype pass -->
            <div class="input_wrapper">
            <?php echo $this->formLabel($this->element->retypePassword->getName(), $this->element->retypePassword->getLabel());?>
            <?php echo $this->{$this->element->retypePassword->helper}(
			$this->element->retypePassword->getName(),
                	$this->element->retypePassword->getValue(),
			$this->element->retypePassword->getAttribs()
		);
            ?>	
            <?php if(($this->element->retypePassword->getMessages())){ echo  $this->formErrors($this->element->retypePassword->getMessages());} 
            ?>
            </div>	
            <div class="clear"></div>	
            <?php echo $this->{$this->element->savePassword->helper}(
                   	$this->element->savePassword->getName(),
			$this->element->savePassword->getValue(),
			$this->element->savePassword->getAttribs()
            );?>
        </div>
  </form>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#formAccountEditPassword').validationEngine('attach', {promptPosition: "centerRight"});	
});

</script>